spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devDB
    username: root
    password: root
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

fileRepositoryFolder: D:\\Eclipse\\Eclipse progetti\\FileRepositoryEsServiziFileUpload